### ISSUE TITLE
It keeps crashing because the config version needs to be 8 or later?

### ISSUE THREAD

**Issue by RandomDiG** [Draradech/FlowerMap#5]
it keeps crashing because the config version needs to be 8 or later? I am dumb, I don't understand what that is telling me

**Comment by RandomDiG** [comment]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config, version 8 or later.
Unmet dependency listing:
	 - Mod 'Flower Map' (flowermap) 1.3.0 requires version 8 or later of cloth-config, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

This the error

**Comment by Draradech** [comment]
You need to install cloth config API v8 or higher (what ever is the newest for your current minecraft version). https://modrinth.com/mod/cloth-config
