### ISSUE TITLE
Map freezes 

### ISSUE THREAD

**Issue by ShakedICE** [Draradech/FlowerMap#6]
When i join the server that i play on the map just freezes 
Singleplayer works but when i rejoin singleplayer after i have been on the server it just continues to be frozen
https://github.com/user-attachments/assets/5b7594ba-e5e6-46ef-a8b9-913fe8fdef02
  
And i get this error in the logs:
`[15:45:29] [Thread-35/ERROR]: Uncaught exception in thread "Thread-35"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_37908()" because "this.minecraft.field_1724" is null
	at de.draradech.flowermap.FlowerMapRenderer.renderTexture(FlowerMapRenderer.java:102) ~[flowermap-1.3.0.temp.jar:?]
	at de.draradech.flowermap.FlowerMapRenderer$1.run(FlowerMapRenderer.java:75) ~[flowermap-1.3.0.temp.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by Draradech** [comment]
I can't reproduce this locally.

flowermap 1.3.0 is for Minecraft 1.20 - 1.20.4, what version are you playing on?

1724 is "player", 37908 is "level()". So it's saying it can't call level(), because player is null. Thing is, when player is null (main menu, for example), the map isn't rendering. Does that always happen or only sometimes?

**Comment by Draradech** [comment]
Closing for inactivity. Feel free to reopen if this is still a problem for you.
